---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: app-nodejs
  namespace: app-project
  labels:
    app: app-nodejs
    team: team1
    catagory: webapp
spec:
  channel: app-entitlement/github-ibm-charts
  name: stable/ibm-nodejs-sample       # The name of the helm chart from the repo
  packageFilter:
    version: "2.0.x"
  placement:
    # clusterSelector:
    #   matchLabels:
    #     cluster: managed-app-cluster
    #     environment: PROD
    placementRef:
      name: app-nodejs-prod
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: default
  packageOverrides:
  - packageName: nodejs-prod
    packageOverrides:
    - path: spec.values
      value: |
        service:
          type: ClusterIP

---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-nodejs
  namespace: app-project
  labels:
    app: app-nodejs
    team: team1
    catagory: webapp
spec:
  selector:
    matchLabels:
      app: app-nodejs
      team: team1
      catagory: webapp
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription

---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: app-nodejs-prod
  namespace: app-project
  labels:
    app: app-nodejs
    team: team1
    catagory: webapp
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      cluster: managed-app-cluster
      environment: PROD
