---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: app-guestbook
  namespace: app-project
  labels:
    app: app-guestbook
    team: team1
    catagory: webapp
spec:
  channel: app-entitlement/custom-charts
  name: guestbook     # The name of the helm chart from the repo
  packageFilter:
    version: "0.2.1"
  placement:
    placementRef:
      name: app-guestbook-prod
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: default
  packageOverrides:
  - packageName: guestbook
    packageOverrides:
    - path: spec.values
      value: |
        service:
          type: NodePort
        redis:
          slaveEnabled: false

---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-guestbook
  namespace: app-project
  labels:
    app: app-guestbook
    team: team1
    catagory: webapp
spec:
  selector:
    matchLabels:
      app: app-guestbook
      team: team1
      catagory: webapp
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription

---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: app-guestbook-prod
  namespace: app-project
  labels:
    app: app-guestbook
    team: team1
    catagory: webapp
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      cluster: managed-app-cluster
      environment: PROD
