---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: bookinfo-charts
  namespace: app-entitlement
spec:
  pathname: https://raw.githubusercontent.com/dymaczew/charts/master/repo/incubator/
  configRef:
    name: insecure-skip-verify
  type: HelmRepo
---
apiVersion: v1
data:
  insecureSkipVerify: "true"
kind: ConfigMap
metadata:
  name: insecure-skip-verify
  namespace: app-entitlement
